---
name: Test

on:
  push:
    branches:
      - master
    tags: ['*']
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v3.5.1

      - name: Install Nix
        uses: cachix/install-nix-action@v20

      - name: Run pre-commit hooks
        run: nix-shell --pure --run 'pre-commit run --all-files'

  test:
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        perl:
          - '5.34'
          - '5.32'
          - '5.30'
          - '5.28'
        os:
          - ubuntu-20.04
          - ubuntu-22.04
        release:
          - focal
          - jammy
    steps:
      - name: Check out repository
        uses: actions/checkout@v3.5.1
        with:
          fetch-depth: 0

      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1.20.2
        with:
          perl-version: ${{ matrix.perl }}

      - name: Install debian dependencies
        run: |
          sudo apt-get --assume-yes -qq install --no-install-recommends \
              cpanminus \
              debhelper \
              fakeroot \
              libtest-exception-perl

      - name: Install Perl dependencies
        run: cpanm Test::Cmd Test::Exception Module::Build

      - name: Build perl
        run: ./configure.bash

      - name: Build
        run: make

      - name: Test build
        run: make check RUNTESTFLAGS=--verbose

      - name: Install
        run: sudo -E make install

      - name: Build distribution
        run: make dist

      - name: Run distribution checks
        run: make distcheck

      - name: Run distribution test
        run: make disttest

      - name: Build packages for all supported versions
        uses: linz/linz-software-repository@v15
        with:
          release: ${{ matrix.release }}

      - name: Test packaging
        run: sudo dpkg -i build-area/liblinz-utils-perl*.deb

  package:
    needs: test
    name: Package for ${{ matrix.release }} on ${{ matrix.runner }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - release: focal
            runner: ubuntu-20.04
          - release: jammy
            runner: ubuntu-22.04
      max-parallel: 1
    steps:
      - uses: actions/checkout@v3.5.1
        with:
          fetch-depth: 0 # Enable the changelog generator to check out previous branch

      - name: Determine packagecloud publication target
        run: |
          # TODO: it would be nice to turn this into a single-liner in
          #       github-action syntax
          echo "GitHub ref: ${{ github.ref }}"
          echo "GitHub event_name: ${{ github.event_name }}"
          PACKAGECLOUD_REPOSITORY=
          if test "${{ github.event_name }}" = 'push'; then
            if expr "${{ github.ref }}" : "refs/tags/" > /dev/null; then
              PACKAGECLOUD_REPOSITORY=test
              git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
            elif test "${{ github.ref }}" = 'refs/heads/packagecloud' \
                   -o "${{ github.ref }}" = 'refs/heads/master'
            then
              PACKAGECLOUD_REPOSITORY=dev
            fi
          fi
          echo "PACKAGECLOUD_REPOSITORY=$PACKAGECLOUD_REPOSITORY" | tee -a $GITHUB_ENV

      - uses: linz/linz-software-repository@v15
        with:
          release: ${{ matrix.release }}
          packagecloud_token: ${{ secrets.LINZCI_PACKAGECLOUD_TOKEN }}
          packagecloud_repository: ${{ env.PACKAGECLOUD_REPOSITORY }}
          push_to_git_remote: origin

  finalise:
    if: always()
    needs:
      - lint
      - test
      - package
    runs-on: ubuntu-22.04
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
